HTSLIB_INSTALL_PATH=
LIBDEFLATE_INSTALL_PATH=


export LD_LIBRARY_PATH=$HTSLIB_INSTALL_PATH/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HTSLIB_INSTALL_PATH/lib64:$LD_LIBRARY_PATH
export INCLUDE=$HTSLIB_INSTALL_PATH/include:$INCLUDE
export CPATH=$HTSLIB_INSTALL_PATH/include:$CPATH

export LD_LIBRARY_PATH=$LIBDEFLATE_INSTALL_PATH/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LIBDEFLATE_INSTALL_PATH/lib64:$LD_LIBRARY_PATH
export INCLUDE=$LIBDEFLATE_INSTALL_PATH/include:$INCLUDE
export CPATH=$LIBDEFLATE_INSTALL_PATH/include:$CPATH

